
import { jsPDF } from "jspdf";
import { User } from "@/types/user";

export const generateHealthCardPDF = (user: User): void => {
  if (!user) return;

  const doc = new jsPDF();
  
  // Set background color
  doc.setFillColor(255, 240, 245); // Light pink background
  doc.rect(0, 0, 210, 297, 'F');
  
  // Add card title
  doc.setFontSize(22);
  doc.setTextColor(33, 33, 33);
  doc.text("संगात Health Card", 105, 20, { align: "center" });
  
  // Add user info
  doc.setFontSize(16);
  doc.text(`Name: ${user.name}`, 20, 40);
  doc.text(`ID: ${user.id}`, 20, 50);
  
  // Add contact details
  doc.setFontSize(12);
  doc.text(`Email: ${user.email}`, 20, 65);
  doc.text(`Phone: ${user.phone || 'Not provided'}`, 20, 75);
  doc.text(`Address: ${user.address || 'Not provided'}`, 20, 85);
  
  // Add medical details
  doc.setFontSize(14);
  doc.text("Medical Information", 20, 105);
  
  doc.setFontSize(12);
  doc.text(`Age: ${user.age || 'Not provided'} years`, 20, 120);
  doc.text(`Height: ${user.height || 'Not provided'} cm`, 20, 130);
  doc.text(`Weight: ${user.weight || 'Not provided'} kg`, 20, 140);
  doc.text(`Blood Group: ${user.bloodGroup || 'Not provided'}`, 20, 150);
  
  // Add medical conditions
  if (user.medicalConditions && user.medicalConditions.length > 0) {
    doc.text("Medical Conditions:", 20, 165);
    user.medicalConditions.forEach((condition, index) => {
      doc.text(`• ${condition}`, 30, 175 + (index * 8));
    });
  } else {
    doc.text("Medical Conditions: None reported", 20, 165);
  }
  
  // Add footer
  doc.setFontSize(10);
  doc.text("Generated by संगात - Your Health Partner", 105, 280, { align: "center" });
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 105, 285, { align: "center" });
  
  // Save the PDF
  doc.save(`Sangaat_Health_Card_${user.name.replace(/\s+/g, '_')}.pdf`);
};
