// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcbhqgdyooyxipbfbqrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYmhxZ2R5b295eGlwYmZicXJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTM5NDYsImV4cCI6MjA1OTg4OTk0Nn0.QJAeZQRa6vGxnV2W18f80i7-ea1ZfPfY4F1yhFYkzTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);